### PR TITLE
add branch3ff file for test

### PR DESCRIPTION
**Pull request by shenya1x**
add branch3ff file for test

Tracked-On: OAM-67575
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by forintegrationtests — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (gordon_peak) - extra

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/156

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/157

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:cancelled Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/159

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/160

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of changes is different than the one in the preintegration.
Errors:
  ('github', 'sysctstage/device-androidia-mixins', 69) preintegration patchset:44e5f95, currentpatchset:dd9c3a7..770a2b3

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/47

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/161

**Review by sysctstage — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/162

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of changes is different than the one in the preintegration.
Errors:
  ('github', 'sysctstage/device-androidia-mixins', 69) preintegration patchset:dd9c3a7..863d38d, currentpatchset:dd9c3a7..decf259

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/48

**Review by sysctstage — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/163

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/164

**Review by sysctstage — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/165

Done by "Shen, YangX" <yangx.shen@intel.com>

**Review by shenya1x — COMMENTED** [review]
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-premerge/builds/49

Done by "Shen, YangX" <yangx.shen@intel.com>

**Pull request merged**
