### PR TITLE
add test for sprint 6.13

### PR DESCRIPTION
**Pull request by shenya1x**
add test for sprint 6.13

Tracked-On: OAM-66830
Signed-off-by: shenya1x <yangx.shen@intel.com>

### CODE REVIEW

**Review by forintegrationtests — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Trigger Builds Triggered: build-cel - r1 (gordon_peak) - extra, build-cel - r1 (gordon_peak_acrn)

For more information, see: /absp-staging/builders/opensource-autobuild/builds/234

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: Trigger Builds Triggered: build-cel - r1 (gordon_peak) - extra, build-cel - r1 (gordon_peak_acrn)

For more information, see: /absp-staging/builders/opensource-autobuild/builds/235

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Create pub Artifactory Generate multi manifest original json

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/0

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-for_integration_tests - r1 (gordon_peak) - extra

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/2

**Pull request merged**
