### PR TITLE
10-10-1

### PR DESCRIPTION
**Pull request by xizhan4x**
Tracked-On: OAM-70152

Signed-off-by: xizhan4x <xix.zhang@intel.com>

### CODE REVIEW

**Review by jzhou3x — APPROVED** [review]
qa

**Review by sysctstage — COMMENTED** [review]
cactus finished building and testing your changes 

It was requested for merge by "Zhang, XiX" <xix.zhang@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp-staging/builders/opensource-mergerequest/builds/442

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Create pub Artifactory Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/844

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: Create pub Artifactory Generate multi manifest original json

For more information, see: /absp-staging/builders/opensource-autobuild/builds/844

**Pull request merged**
