### PR TITLE
Create keke

### PR DESCRIPTION
**Pull request by kewenchao**
Tracked-On: OAM-67232
Signed-off-by: kewenchx wenchao.ke@intel.com

### CODE REVIEW

**Review by sysctstage — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/509

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

Cactus automatically verified this PR.

For more information, see: /absp-staging/builders/opensource-autobuild/builds/511

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/140

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/141

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/142

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Compute Dependencies Compute Deps failed

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/149

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:Compute Dependencies Compute Deps failed

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/150

**Pull request closed without merging**
